spring:
  #Resource server configuration
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/mini2

# Keycloak configuration
keycloak:
  realm: mini2
  resource: keycloak-client
  auth-server-url: http://localhost:8080/
  credentials:
    secret: 8uof3O0CScR9jogN6QqoRoWc9Kk2eP21
    client-id: mini
    provider: secret
# Swagger configuration
springdoc:
  swagger-ui:
    oauth:
      client-id: mini
      client-secret: 8uof3O0CScR9jogN6QqoRoWc9Kk2eP21
      realm: mini2