server:
  port: 9797
spring:
  application:
    name: keycloak-admin-client
  #Resource server configuration
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/keycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#          jwk-set-uri: http://localhost:8080/realms/myauth/protocol/openid-connect/certs
# Keycloak configuration
keycloak:
  realm: keycloak
  resource: keycloak
  auth-server-url: http://localhost:8080/
  credentials:
    secret: F0yYvuswdi0JgH1kLMY3QkNCJNDoJyho
    client-id: keycloak-client
    provider: secret
# Swagger configuration
springdoc:
  swagger-ui:
    oauth:
      client-id: keycloak-client
      client-secret: F0yYvuswdi0JgH1kLMY3QkNCJNDoJyho
      realm: keycloak
    tags-sorter: alpha
