#port
server:
  port: 9091

#Application name
spring:
  application:
    name: keycloak-admin-client

  #Resource Server Configuration
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/keycloak
          jwk-set-uri: http://localhost:8080/realms/keycloak/protocol/openid-connect/certs

  #Keycloak Configuration
keycloak:
  realm: keycloak
  resource: keycloak-client
  auth-server-url: http://localhost:8080/auth #Docker Container
  credentials:
    secret: F0yYvuswdi0JgH1kLMY3QkNCJNDoJyho
    client-id: keycloak-client
    provider: secret

    #Eureka client configuration
    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka

# Swagger Configuration
springdoc:
  swagger-ui:
    oauth:
      client-id: keycloak-client
      client-secret: F0yYvuswdi0JgH1kLMY3QkNCJNDoJyho
      realm: keycloak
    tags-sorter: alpha

